version: "3.0"

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
      MYSQL_DATABASE: vollmed_api
      MYSQL_ROOT_PASSWORD: root